version: "2.1"

services:
  pdns:
    build: .
    image: localhost/psitrax/powerdns:4.1.0
    restart: always 
    ports:
     - "53:53"
     - "53:53/udp"
     - "8081:8080"
    environment:
     - MYSQL_HOST=db   
     - MYSQL_USER=root
     - MYSQL_PASS=supersecret
    depends_on:
     - db

  db:
    image: mariadb:10.1
    environment:
     - MYSQL_ROOT_PASSWORD=supersecret

  rtb-powerdns-connector:
    image: docker.rtbrick.com/rtb-powerdns-connector:0.0.2
    restart: always
    ports:
      - 19991:19991
    environment:
      - powerdns_base_url=http://pdns:8080
    depends_on:
      - pdns